(define (read-while-eof)
  (let ((res (read)))
    (if (eof-object? res)
	()
	(cons res (read-while-eof)))))


(define headers
  '(
    (define lisp-nil
      (lambda (x)
	"lisp-nil"))
    (define (cons car cdr)
      (lambda (x)
	(cond ((= x "lisp-car") car)
	      ((= x "lisp-cdr") cdr)
	      ((= x "lisp-type") "lisp-cons"))))
    (define (car c)
      (c "lisp-car"))
    (define (cdr c)
      (c "lisp-cdr"))
    (define (null? x)
      (and (procedure? x)
	   (= (x "lisp-type") "lisp-nil")))
    (define (pair? x)
      (and (procedure? x)
	   (= (x "lisp-type") "lisp-cons")))
    (define (list? x)
      (or (null? x) (pair? x)))
    (define (length lst)
      (if (null? lst)
	  0
	  (+ 1 (length (cdr lst)))))
    (define (reverse lst)
      (define (rec lst acc)
	(if (null? lst)
	    acc
	    (rec (cdr lst) (cons (car lst) acc))))
      (rec lst ()))
    (define (map1 f lst)
      (if (null? lst)
	  ()
	  (cons (f (car lst))
		(map1 f (cdr lst)))))
    (define (list . list-elements)
      list-elements)
    (define (every f . lists)
      (define (finish? lists)
	(if (null? lists)
	    #f
	    (or (null? (car lists))
		(finish? (cdr lists)))))
      (define (rec lists)
	(or (finish? lists)
	    (and (apply f (map1 car lists))
		 (rec (map1 cdr lists)))))
      (rec lists))
    (define (some f . lists)
      (define (finish? lists)
	(if (null? lists)
	    #f
	    (or (null? (car lists))
		(finish? (cdr lists)))))
      (define (rec lists)
	(if (finish? lists)
	    #f
	    (or (apply f (map1 car lists))
		(rec (map1 cdr lists)))))
      (rec lists))
    (define (append . lsts)
      (define (rec1 lsts)
	(cond ((= 0 (length lsts)) ())
	      ((= 1 (length lsts)) (car lsts))
	      (else (rec2 (car lsts) (cdr lsts)))))
      (define (rec2 lst lsts)
	(if (null? lst)
	    (rec1 lsts)
	    (cons (car lst) (rec2 (cdr lst) lsts))))
      (rec1 lsts))
    (define (map f . lists)
      (if (some null? lists)
	  lisp-nil
	  (cons (apply f (map1 car lists))
		(apply map f (map1 cdr lists)))))
    ))


(map (lambda (line)
       (write line)
       (newline))
     (append headers
	     (read-while-eof)))

(procedure? identity)
